[project]
name = "zenpay"
version = "0.1.0"
description = "Client SDK for ZenPay usage billing"
authors = [{ name="Your Name", email="you@example.com" }]
dependencies = ["requests"]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
